export enum ActionType {
    UPDATE_POSITION = "UPDATE_POSITION",
    UPDATE_VIEWPORT_SIZE = "UPDATE_VIEWPORT_SIZE",
    UPDATE_SPIN_STATUS = "UPDATE_SPIN_STATUS",
    TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
    SET_EDIT_SLICE = "SET_EDIT_SLICE",
  }
  