export enum ActionType {
    UPDATE_POSITION = "UPDATE_POSITION",
    UPDATE_VIEWPORT_SIZE = "UPDATE_VIEWPORT_SIZE",
    UPDATE_SPIN_STATUS = "UPDATE_SPIN_STATUS",
    TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
    UPDATE_WHEEL_SLICE = "UPDATE_WHEEL_SLICE",
  }
  